name: individual_project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  salomon_bottom_bar: ^3.0.0
  get: ^4.6.6
  flutter_custom_clippers: ^2.1.0
  item_count_number_button: ^1.9.2
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.2.2
  flutter_credit_card: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  path: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logoicon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/images/logoicon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/drink/
    - lib/assets/images/pizza/
    - lib/assets/images/snacks/
    - lib/assets/images/profile1.jpg
